SELECT record_id,
	   law_id,
       bill_id,
       bill_page_url,
	   bill_title,
       origin_type,
       procedure_type_standard,
       procedure_type_national,
       CASE WHEN original_law = true THEN 'true' WHEN original_law = false THEN 'false' END original_law,
       bill_type,
       bill_status,
       modified_laws_count,
       affecting_laws_count,
       affecting_laws_first_date,
       date_introduction,
       stages_count,
       date_passing,
       date_entering_into_force,
       committee_count,
       committee_hearing_count,
       ia_dummy,
       bill_size,
       bill_text_url,
       law_size,
       law_text_url,
       amendment_count,
       plenary_size,
       final_vote_for,
       final_vote_against,
       final_vote_abst
FROM legislative_data_pl2.bill_main_table
ORDER BY record_id;